### ISSUE TITLE
Decide on name

### ISSUE THREAD

**Issue by skalee** [riboseinc/stronger_parameters#2]
In riboseinc/rack-cleanser#25, we've decided to create a brand new gem for controller action parameters. We need to pick name for it. Some discussion happened in the aforelinked issue:

@skalee:
> Then I'm starting a new gem for that. Regarding gem name, any ideas? Maybe "(Rails) Parameter Constraints"? Or "Stronger Parameters"?

@ronaldtse
> Some on top of my head: "structured_parameters", "parameters_validation"

For now it's Stronger Parameters, but I'm open for hints.

cc @ribose-jeffreylau

**Comment by ribose-jeffreylau** [comment]
🎉 Thanks @skalee for creating the gem!
Stronger Parameters is the more memorable and catchier option for now.  I'm OK with keeping it. 👍

**Comment by ronaldtse** [comment]
@skalee yes let's keep this. Will perform the tasks mentioned. Thanks!

**Comment by skalee** [comment]
Wow, just noticed that Stronger Parameters (https://rubygems.org/gems/stronger_parameters) is already taken. And possibly the gem with this name does what you need. I need to take a closer look.

**Comment by skalee** [comment]
Yes, it appears to be quite mature, somewhat popular, and maintained. Last commit is from June. It works with and is tested against Ruby 2+ and Rails 3+.

I think it supports whatever required for most cases, including string format or maximum length checks, though not everything is well-documented. If needed, I can develop additional constraints.

**Comment by ribose-jeffreylau** [comment]
👍 
Good find.  https://rubygems.org/gems/stronger_parameters does seem quite capable.

P.S. I knew Stronger Parameters would be a good name 😉

**Comment by ronaldtse** [comment]
It looks like it does most of the things we want -- is there anything we can add or should we just consider this solved?

**Comment by skalee** [comment]
@ronaldtse I guess it's solved. If you have further requests, I guess I can enhance that other gem. For instance, I could improve docs, or add some generic lambda-accepting matcher similar to [RSpec's `satisfy` matcher](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/satisfy-matcher).
